services:
  ollama:
    build:
      context: ./docker/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=gemma:2b
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    restart: unless-stopped

  app:
    build:
      context: ./src/app
    container_name: zerobot-app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CHROMA_HOST=http://chromadb:8000
      - OLLAMA_MODEL=gemma:2b
    volumes:
      - app_data:/app/data
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
  app_data:
